version: "3.8"

services:
    db:
        container_name: postgresql_app
        profiles:
          - db
          - all
        build:
          context: devops/postgres
          dockerfile: Dockerfile
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 10s
        ports:
          - "5432:5432"
        env_file:
          - "src/backend/.env"

    redis_db:
        container_name: redis_app
        profiles:
          - all
          - db
        build:
          context: devops/redis
          dockerfile: Dockerfile
        restart: "unless-stopped"
        healthcheck:
          test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        ports:
          - "6379:6379"

    backend:
        container_name: backend_main
        profiles:
          - app
          - all
        build:
          context: .
          dockerfile: devops/backend/Dockerfile
        restart: "unless-stopped"
        ports:
          - "80:80"
        depends_on:
          db:
            condition: service_healthy
          redis_db:
            condition: service_healthy
